# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retrieval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retrieval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretrieval.proto\x12\tretrieval\"U\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12\x15\n\rdocument_type\x18\x03 \x01(\t\x12\t\n\x01k\x18\x04 \x01(\x05\"{\n\x12MultiSearchRequest\x12\x0f\n\x07queries\x18\x01 \x03(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12\x15\n\rdocument_type\x18\x03 \x01(\t\x12\x13\n\x0bk_per_query\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65\x64uplicate\x18\x05 \x01(\x08\"i\n\x0eSearchResponse\x12 \n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x10.retrieval.Chunk\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x99\x01\n\x05\x43hunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x30\n\x08metadata\x18\x03 \x03(\x0b\x32\x1e.retrieval.Chunk.MetadataEntry\x12\r\n\x05query\x18\x04 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x14\n\x12HealthCheckRequest\";\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cvector_store\x18\x02 \x01(\t2\xe8\x01\n\x10RetrievalService\x12=\n\x06Search\x12\x18.retrieval.SearchRequest\x1a\x19.retrieval.SearchResponse\x12G\n\x0bMultiSearch\x12\x1d.retrieval.MultiSearchRequest\x1a\x19.retrieval.SearchResponse\x12L\n\x0bHealthCheck\x12\x1d.retrieval.HealthCheckRequest\x1a\x1e.retrieval.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrieval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNK_METADATAENTRY']._loaded_options = None
  _globals['_CHUNK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=30
  _globals['_SEARCHREQUEST']._serialized_end=115
  _globals['_MULTISEARCHREQUEST']._serialized_start=117
  _globals['_MULTISEARCHREQUEST']._serialized_end=240
  _globals['_SEARCHRESPONSE']._serialized_start=242
  _globals['_SEARCHRESPONSE']._serialized_end=347
  _globals['_CHUNK']._serialized_start=350
  _globals['_CHUNK']._serialized_end=503
  _globals['_CHUNK_METADATAENTRY']._serialized_start=456
  _globals['_CHUNK_METADATAENTRY']._serialized_end=503
  _globals['_HEALTHCHECKREQUEST']._serialized_start=505
  _globals['_HEALTHCHECKREQUEST']._serialized_end=525
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=527
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=586
  _globals['_RETRIEVALSERVICE']._serialized_start=589
  _globals['_RETRIEVALSERVICE']._serialized_end=821
# @@protoc_insertion_point(module_scope)
